name: tests

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install Deps
        run: |
          pip install pylint
          pip install mypy
          pip install -r requirements.txt
          pip install .[test]

      - name: Run Linter
        run: pylint ./statsig --rcfile .pylintrc

      - name: Run Type Checker
        run: |
          pip install types-requests
          pip install types-redis
          pip install types-protobuf
          mypy ./statsig --ignore-missing-imports --check-untyped-defs --exclude ./build/lib,./statsig/grpc

      - name: Run Tests
        run: python3 -m unittest discover -s ./tests --verbose
        env:
          test_api_key: ${{ secrets.SDK_CONSISTENCY_TEST_COMPANY_API_KEY }}
          test_client_key: ${{ secrets.KONG_CLIENT_SDK_KEY }}


